name: Docs

on:
  push:
    branches:
      - next
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Typedoc
        run: |
          npm ci
          npm run docs
        env:
          CI: true
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: out
        env:
          GH_PAT: ${{ secrets.GH_TOKEN }}
